import type { Category, Product } from '@/types'

// Sanity integration: replace these with GROQ queries

export const categories: Category[] = [
  {
    id: 'cat-1',
    slug: 'luxury-lawn',
    name: 'Luxury Lawn',
    description: 'Ready-to-wear lawn suits crafted with care for the discerning woman',
    imgVariant: 'warm-1',
  },
  {
    id: 'cat-2',
    slug: 'ready-to-wear',
    name: 'Ready to Wear',
    description: 'Effortless, refined, and enduring — pieces made for the modern Pakistani woman',
    imgVariant: 'warm-5',
  },
  {
    id: 'cat-3',
    slug: 'formals',
    name: 'Formals',
    description: 'Elegant formal wear for every special occasion',
    imgVariant: 'dark-1',
  },
]

export const products: Product[] = [
  // Luxury Lawn
  {
    id: 'p-001',
    slug: 'embroidered-lawn-ell-9133',
    name: 'Embroidered Lawn ELL-9133',
    sku: 'ELL-9133',
    price: 7800,
    originalPrice: 9500,
    category: 'Luxury Lawn',
    categorySlug: 'luxury-lawn',
    description: 'A refined three-piece lawn suit featuring delicate machine embroidery on the shirt front, paired with a printed dupatta and plain trouser. Perfect for daytime gatherings.',
    fabric: 'Premium Lawn',
    pieces: 3,
    isNew: true,
    isFeatured: true,
    imgVariant: 'warm-1',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p-002',
    slug: 'floral-printed-lawn-ell-9240',
    name: 'Floral Printed Lawn ELL-9240',
    sku: 'ELL-9240',
    price: 6200,
    category: 'Luxury Lawn',
    categorySlug: 'luxury-lawn',
    description: 'Delicate floral motifs rendered in soft pastels on ultra-fine lawn. This three-piece includes a digitally printed shirt, coordinated dupatta, and dyed trouser.',
    fabric: 'Fine Lawn',
    pieces: 3,
    isFeatured: true,
    imgVariant: 'warm-2',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'p-003',
    slug: 'hand-block-lawn-ell-9358',
    name: 'Hand Block Lawn ELL-9358',
    sku: 'ELL-9358',
    price: 8500,
    category: 'Luxury Lawn',
    categorySlug: 'luxury-lawn',
    description: 'Traditional hand-block printing meets contemporary silhouettes. Each print is unique, celebrating the heritage of Pakistani textile artisans.',
    fabric: 'Swiss Lawn',
    pieces: 3,
    isNew: true,
    imgVariant: 'warm-3',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p-004',
    slug: 'gul-e-bahar-lawn-ell-9401',
    name: 'Gul-e-Bahar Lawn ELL-9401',
    sku: 'ELL-9401',
    price: 9200,
    originalPrice: 11000,
    category: 'Luxury Lawn',
    categorySlug: 'luxury-lawn',
    description: 'Named after the spring bloom, this piece features a digitally printed shirt with delicate floral embroidery at the neckline and sleeves, finished with a matching chiffon dupatta.',
    fabric: 'Lawn + Chiffon Dupatta',
    pieces: 3,
    isRestocked: true,
    isFeatured: true,
    imgVariant: 'warm-4',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p-005',
    slug: 'summer-bloom-lawn-ell-9512',
    name: 'Summer Bloom Lawn ELL-9512',
    sku: 'ELL-9512',
    price: 7100,
    category: 'Luxury Lawn',
    categorySlug: 'luxury-lawn',
    description: 'A fresh interpretation of classic lawn prints with bold geometric patterns and floral accents in a soft, wearable palette.',
    fabric: 'Premium Lawn',
    pieces: 3,
    imgVariant: 'warm-5',
    sizes: ['S', 'M', 'L', 'XL'],
  },

  // Ready to Wear
  {
    id: 'p-016',
    slug: 'linen-co-ord-rtw-4411',
    name: 'Linen Co-Ord RTW-4411',
    sku: 'RTW-4411',
    price: 8900,
    category: 'Ready to Wear',
    categorySlug: 'ready-to-wear',
    description: 'Effortlessly chic linen co-ordinate — a relaxed kurta paired with wide-leg trousers. Minimal kachha dhaga embroidery at the neckline adds quiet refinement.',
    fabric: 'Premium Linen',
    pieces: 2,
    isNew: true,
    isFeatured: true,
    imgVariant: 'warm-5',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p-017',
    slug: 'printed-pret-kurta-rtw-4523',
    name: 'Printed Pret Kurta RTW-4523',
    sku: 'RTW-4523',
    price: 5400,
    category: 'Ready to Wear',
    categorySlug: 'ready-to-wear',
    description: 'A versatile everyday kurta in digital floral print on soft cotton. The A-line silhouette flatters all figures — clean and enduring.',
    fabric: 'Cotton Lawn',
    pieces: 1,
    imgVariant: 'warm-6',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'p-018',
    slug: 'fusion-pret-set-rtw-4678',
    name: 'Fusion Pret Set RTW-4678',
    sku: 'RTW-4678',
    price: 11200,
    originalPrice: 13500,
    category: 'Ready to Wear',
    categorySlug: 'ready-to-wear',
    description: 'A cropped kameez with wide palazzo trousers in a block-print earth-tone palette. Thoughtful tailoring, effortless to wear.',
    fabric: 'Cotton Satin',
    pieces: 2,
    isRestocked: true,
    isFeatured: true,
    imgVariant: 'warm-7',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p-019',
    slug: 'embellished-pret-top-rtw-4801',
    name: 'Embellished Pret Top RTW-4801',
    sku: 'RTW-4801',
    price: 6800,
    category: 'Ready to Wear',
    categorySlug: 'ready-to-wear',
    description: 'A semi-formal top with delicate hand-embellished details at the collar and cuffs. Premium fabric, restrained design — from day to evening.',
    fabric: 'Tissue + Silk Blend',
    pieces: 1,
    isNew: true,
    imgVariant: 'warm-8',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p-020',
    slug: 'classic-pret-suit-rtw-4934',
    name: 'Classic Pret Suit RTW-4934',
    sku: 'RTW-4934',
    price: 9600,
    category: 'Ready to Wear',
    categorySlug: 'ready-to-wear',
    description: 'The quintessential ready-to-wear suit for the modern Pakistani woman. Fine cotton with contrast piping — refined simplicity at its best.',
    fabric: 'Fine Cotton',
    pieces: 3,
    isFeatured: true,
    imgVariant: 'blush',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },

  // Formals
  {
    id: 'p-011',
    slug: 'kamdani-formal-fml-1122',
    name: 'Kamdani Formal FML-1122',
    sku: 'FML-1122',
    price: 18000,
    category: 'Formals',
    categorySlug: 'formals',
    description: 'A statement piece for cherished occasions — kamdani embellishment on rich fabric with a matching dupatta. Ready-to-wear formal.',
    fabric: 'Velvet + Net Dupatta',
    pieces: 3,
    isNew: true,
    isFeatured: true,
    imgVariant: 'dark-1',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p-012',
    slug: 'resham-gharara-fml-1258',
    name: 'Resham Gharara FML-1258',
    sku: 'FML-1258',
    price: 15500,
    originalPrice: 18000,
    category: 'Formals',
    categorySlug: 'formals',
    description: 'Resham embroidery on a gharara set — a nod to traditional craftsmanship with a modern silhouette. Ready-to-wear, not stitched to order.',
    fabric: 'Raw Silk',
    pieces: 2,
    isFeatured: true,
    imgVariant: 'dark-2',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'p-013',
    slug: 'chiffon-formal-fml-1374',
    name: 'Chiffon Formal FML-1374',
    sku: 'FML-1374',
    price: 13200,
    category: 'Formals',
    categorySlug: 'formals',
    description: 'Flowing chiffon with gulkari embroidery across the front panel and sleeves. Elegant, sophisticated, ready to wear.',
    fabric: 'Chiffon + Silk Lining',
    pieces: 3,
    isRestocked: true,
    imgVariant: 'dark-3',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p-014',
    slug: 'angrakha-formal-fml-1490',
    name: 'Angrakha Formal FML-1490',
    sku: 'FML-1490',
    price: 16200,
    category: 'Formals',
    categorySlug: 'formals',
    description: 'The Angrakha silhouette in finest handloom silk. Gota patti borders frame the crossover front — regal and timeless.',
    fabric: 'Pure Handloom Silk',
    pieces: 2,
    isNew: true,
    imgVariant: 'cool-3',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'p-015',
    slug: 'noor-e-shab-formal-fml-1605',
    name: 'Noor-e-Shab Formal FML-1605',
    sku: 'FML-1605',
    price: 17500,
    originalPrice: 20000,
    category: 'Formals',
    categorySlug: 'formals',
    description: 'Named for the light of night — sequin and crystal embellishments on midnight-toned fabric. Pakistani eveningwear at its finest.',
    fabric: 'Organza + Silk Base',
    pieces: 3,
    isFeatured: true,
    imgVariant: 'cool-4',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug)
}

export function getFeaturedProducts(limit = 5): Product[] {
  return products.filter((p) => p.isFeatured).slice(0, limit)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.categorySlug === product.categorySlug && p.id !== product.id)
    .slice(0, limit)
}

export function getNewArrivals(limit = 8): Product[] {
  return products.filter((p) => p.isNew).slice(0, limit)
}
